#!/usr/bin/env node
import { existsSync, readFileSync } from "node:fs"

const manifestPath = "repos/vendored.json"
const documentPath = "repos/VENDORED.md"

function renderDocument(manifest) {
  const rows = manifest.repos.map(
    (repository) =>
      `| \`${repository.name}\` | ${repository.url} | \`${repository.ref}\` | \`${repository.commit.slice(0, 7)}\` | ${repository.size_mb} MB | ${repository.vendored_at.slice(0, 10)} | ${repository.pins ? `\`${repository.pins.package}\` in \`${repository.pins.from}\`` : "—"} |`,
  )
  return [
    "# Vendored source",
    "",
    "Generated by `vendor-source` from `repos/vendored.json` — do not edit. Everything under `repos/` is read-only reference: read it to see how a library really works, never edit it, never import from it (the seam lint fails), never treat it as work in scope. `vendor-source update` refreshes it.",
    "",
    "| Name | Source | Ref | Commit | Size | Vendored | Pinned by |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    `${manifest.repos.length} vendored repo(s).`,
    "",
  ].join("\n")
}

if (!existsSync(manifestPath)) {
  console.log("nothing vendored")
  process.exit(0)
}

const manifest = JSON.parse(readFileSync(manifestPath, "utf8"))
const problems = []
const versions = {}
for (const repository of manifest.repos) {
  if (!repository.pins) continue
  const { package: packageName, from } = repository.pins
  if (!(from in versions)) {
    const contents = existsSync(from) ? JSON.parse(readFileSync(from, "utf8")) : {}
    versions[from] = { ...(contents.devDependencies ?? {}), ...(contents.dependencies ?? {}) }
  }
  const version = versions[from][packageName]
  const expected = `${packageName}@${version}`
  if (!version) {
    problems.push(`${repository.name}: ${from} no longer lists ${packageName}`)
  } else if (repository.ref !== expected) {
    problems.push(`${repository.name}: expected ${expected}, found ${repository.ref}`)
  }
}
if (
  !existsSync(documentPath)
  || readFileSync(documentPath, "utf8") !== renderDocument(manifest)
) {
  problems.push(`${documentPath} does not match ${manifestPath}`)
}
if (problems.length > 0) {
  console.error(`vendored source is out of step with the repo:\n${problems.map((problem) => `  - ${problem}`).join("\n")}`)
  process.exit(1)
}
console.log(`vendored source is current (${manifest.repos.length} repo(s))`)
